# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_movies_movie_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='movies',
        ),
    ]
