# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='tmdb_id',
            field=models.IntegerField(default=0),
        ),
    ]
