# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160308_1441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='movies',
        ),
    ]
