# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_delete_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(default=0)),
                ('genre', models.CharField(max_length=100)),
                ('movie_name', models.CharField(max_length=100)),
            ],
        ),
    ]
