# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-10 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_movies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='links',
        ),
        migrations.DeleteModel(
            name='movies',
        ),
    ]
