# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-10 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_links_movies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='links',
        ),
    ]
